### ISSUE TITLE
tfprocess.py doesn't work with Tensorflow=>2.4

### ISSUE THREAD

**Issue by CallOn84** [CSSLab/maia-chess#56]
While running train_maia.py on Windows, I came across an issue pertaining to the tfprocess.py file.

tfprocess.py contains `tf.keras.mixed_precision.experimental`, which is doesn't exist if you use TensorFlow that is greater than version 2.4. When you run train_maia.py, it outputs an `AttributeError: module 'keras.api._v2.keras.mixed_precision' has no attribute 'experimental'`.

The offending lines of code you might want to look into changing are the following:

```
- tf.keras.mixed_precision.experimental.set_policy('mixed_float16') - Line 123.
- self.optimizer = tf.keras.mixed_precision.experimental.LossScaleOptimizer(self.optimizer, self.loss_scale) - Line 150.
```

**Comment by PXY0411** [comment]
I wonder if you figure out how to solve those code?

**Comment by CallOn84** [comment]
> I wonder if you figure out how to change those code?

You can see the changes I've made in the pull request. It will need to be tested, though.
